export interface VwCar {
    id?:string;
    productId?:string;
    personId?:string;
    departmentId?:string;
    parentId?:string;
    isActive?:string;
    description?:string;
    createUserID?:string;
    createDate?:Date;
    updateUserID?:string;
    updateDate?:Date;
    partNumber?:string;
    serialNumberVin?:string;
    year?:string;
    type?:string;
    barCode?:string;
    hCAssetHealthStatusId?:string;
    hCAssetQualityId?:string;
    hCunitId?:string;
    pelak?:string;
    star?:string;
    assetInPackage?:string;
    manufactureDate?:Date;
    hCColorId?:string;
    pelak1?:string;
    hcpelakCharacterId?:string;
    pelak2?:string;
    pelak3?:string;
    sign?:string;
    machine?:boolean;
    imageProduct?:string;
    brandId?:string;
    pelakSign?:string;
    brandSign?:string;
    model?:string;
    logo?:string;
    check?:boolean;
    latestUsage: number;
    mroplanActive?: boolean;
    notificationActive?: boolean;
    brandIcon?:string;
    jcUserRejected?:boolean;
    }